import { createHash } from 'node:crypto'
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { spawnSync } from 'node:child_process'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'))
const outputDirectory = join(root, 'dist', 'security')
const outputPath = join(outputDirectory, `${pkg.name}-${pkg.version}.cdx.json`)
const dependencyListPath = join(root, 'THIRD_PARTY_DEPENDENCIES.md')
const npmCommand = process.platform === 'win32' ? 'npm.cmd' : 'npm'

const result = spawnSync(
  npmCommand,
  [
    'sbom',
    '--omit=dev',
    '--sbom-format=cyclonedx',
    '--sbom-type=application',
  ],
  {
    cwd: root,
    encoding: 'utf8',
    env: process.env,
    maxBuffer: 20 * 1024 * 1024,
  },
)

if (result.status !== 0) {
  process.stderr.write(result.stderr || result.stdout || '[sbom] npm sbom failed\n')
  process.exit(result.status ?? 1)
}

const sbom = JSON.parse(result.stdout)
const components = Array.isArray(sbom.components) ? sbom.components : []
const requiredVersions = new Map([
  ['@earendil-works/pi-coding-agent', '0.82.1'],
  ['brace-expansion', '5.0.8'],
  ['protobufjs', '7.6.5'],
  ['proxy-chain', '3.0.0'],
  ['undici', '8.5.0'],
])

for (const [name, version] of requiredVersions) {
  if (!components.some((component) => component.name === name && component.version === version)) {
    console.error(`[sbom] missing required component ${name}@${version}`)
    process.exit(1)
  }
}

const forbiddenVersions = new Map([
  ['brace-expansion', new Set(['5.0.6', '5.0.7'])],
  ['protobufjs', new Set(['7.6.4'])],
])

for (const component of components) {
  if (forbiddenVersions.get(component.name)?.has(component.version)) {
    console.error(`[sbom] vulnerable component remains: ${component.name}@${component.version}`)
    process.exit(1)
  }
}

mkdirSync(outputDirectory, { recursive: true })
const serialized = `${JSON.stringify(sbom, null, 2)}\n`
writeFileSync(outputPath, serialized)
const sha256 = createHash('sha256').update(serialized).digest('hex')

const dependencyRows = components
  .map((component) => {
    const licenses = (component.licenses || [])
      .map((entry) => entry.license?.id || entry.license?.name || entry.expression)
      .filter(Boolean)
      .join(', ')
    if (!licenses) {
      console.error(`[sbom] component has no declared license: ${component.name}@${component.version}`)
      process.exit(1)
    }
    return {
      name: component.name,
      version: component.version,
      licenses,
      purl: component.purl || '',
    }
  })
  .sort((left, right) =>
    `${left.name}@${left.version}`.localeCompare(`${right.name}@${right.version}`),
  )
const dependencyList = `# Production third-party dependency inventory

This file is generated by \`npm run sbom\` from the installed production dependency
tree for Vizruna ${pkg.version}. It records package versions and
declared license identifiers; it is an engineering inventory, not a legal
clearance or a substitute for required license texts and notices.

| Package | Version | Declared license | Package URL |
| --- | --- | --- | --- |
${dependencyRows
  .map(
    (row) =>
      `| ${row.name.replaceAll('|', '\\|')} | ${row.version} | ${row.licenses.replaceAll('|', '\\|')} | ${row.purl} |`,
  )
  .join('\n')}
`
writeFileSync(dependencyListPath, dependencyList)

console.log(`[sbom] wrote ${components.length} production components to ${outputPath}`)
console.log(`[sbom] wrote production dependency inventory to ${dependencyListPath}`)
console.log(`[sbom] sha256 ${sha256}`)
